### ISSUE TITLE
tune the usbswither 

### ISSUE THREAD

**Issue by Leon-aka-KoHb** [FICS/atcmd#10]
Hi! 
First I want to thank for your research activities! What you are doing is really cool.
I have one small question, how to configure usbswitcher for other manufacturers?
I am a beginner in research, and would be very grateful for the tips

**Comment by daveti** [comment]
We actually extended the original usbswitcher to support LG. You could diff the original usbswitcher and our version to find how we did it. In short, you needed to know the USB VID and PID of a phone, and where the modem interface (e.g, cdc_acm) is - config/interface. Note that not every vendor exposes the modem interface by default. Hope it helps.

**Comment by Leon-aka-KoHb** [comment]
> We actually extended the original usbswitcher to support LG. You could diff the original usbswitcher and our version to find how we did it. In short, you needed to know the USB VID and PID of a phone, and where the modem interface (e.g, cdc_acm) is - config/interface. Note that not every vendor exposes the modem interface by default. Hope it helps.

Thank you very much for the answer!
